import 'package:blockchain_utils/utils/numbers/rational/big_rational.dart';
import 'package:tron_energy_wallet_core/tron_energy_wallet_core.dart';

AppAsset baseEthAssetExample({
  required String address,
  required bool supportsEIP1559,
  required bool isMainnet,
}) => AppAsset(
  id: 1225,
  balance: BigRational.one,
  hold: BigRational.zero,
  address: address,
  walletId: 3821,
  childWalletAddress: '',
  token: AppToken(
    id: 551,
    name: 'Ethereum',
    shortName: 'ETH',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png',
    usdPrice: 3003,
    prevPriceDiffPercent: 0.1,
    contractAddress: '',
    decimal: 18,
    precision: 6,
    blockchain: BlockchainInfo(
      id: 190,
      name: 'Base',
      shortName: 'Base',
      icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png',
      isNew: false,
      tokens: [],
      appBlockchain: AppBlockchain.base,
      chainId: isMainnet ? 8453 : 84532,
      networkId: isMainnet ? 8453 : 84532,
      supportsEIP1559: supportsEIP1559,
    ),
    tokenWalletType: TokenWalletType.master,
    description: 'Ethereum on optimism',
    isExchangeable: false,
  ),
);

AppAsset baseUSDCTestnetAssetExample({
  required String address,
  required bool supportsEIP1559,
}) => AppAsset(
  id: 115,
  balance: BigRational.one,
  hold: BigRational.zero,
  address: address,
  walletId: 433,
  childWalletAddress: '',
  token: AppToken(
    id: 543,
    name: 'Base',
    shortName: 'Base',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png',
    usdPrice: 0.9992,
    prevPriceDiffPercent: 0.09,
    contractAddress: '0x036CbD53842c5426634e7929541eC2318f3dCF7e',
    decimal: 6,
    precision: 2,
    blockchain: BlockchainInfo(
      id: 190,
      name: 'Base',
      shortName: 'Base',
      icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png',
      isNew: false,
      tokens: [],
      appBlockchain: AppBlockchain.base,
      chainId: 84532,
      networkId: 84532,
      supportsEIP1559: supportsEIP1559,
    ),
    tokenWalletType: TokenWalletType.child,
    description: 'USDC',
    isExchangeable: false,
  ),
);
