import 'package:blockchain_utils/blockchain_utils.dart';
import 'package:tron_energy_wallet_core/tron_energy_wallet_core.dart';

AppAsset polTestnetAmoyAssetExample({
  required String address,
}) => AppAsset(
  id: 1222,
  balance: BigRational.one,
  hold: BigRational.zero,
  address: address,
  walletId: 11432,
  childWalletAddress: '',
  token: const AppToken(
    id: 254,
    name: 'Polygon',
    shortName: 'POL',
    icon: '',
    usdPrice: 0.3003,
    prevPriceDiffPercent: 0.13,
    contractAddress: '',
    decimal: 18,
    precision: 6,
    blockchain: BlockchainInfo(
      id: 436,
      name: 'Polygon Amoy',
      shortName: 'polygon',
      icon: '',
      isNew: true,
      tokens: [],
      appBlockchain: AppBlockchain.polygon,
      chainId: 80002,
      networkId: 80002,
      supportsEIP1559: true,
    ),
    tokenWalletType: TokenWalletType.master,
    description: 'Polygon',
  ),
);

AppAsset polUSDCCircleTestnetAmoyAssetExample({
  required String address,
}) => AppAsset(
  id: 3234,
  balance: BigRational.one,
  hold: BigRational.zero,
  address: address,
  walletId: 153,
  childWalletAddress: '',
  token: const AppToken(
    id: 235452,
    name: 'USDC',
    shortName: 'USDC',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png',
    usdPrice: 0.9995,
    prevPriceDiffPercent: 0.09,
    contractAddress: '0x41E94Eb019C0762f9Bfcf9Fb1E58725BfB0e7582',
    decimal: 6,
    precision: 2,
    blockchain: BlockchainInfo(
      id: 436,
      name: 'Polygon Amoy',
      shortName: 'polygon',
      icon: '',
      isNew: true,
      tokens: [],
      appBlockchain: AppBlockchain.polygon,
      chainId: 80002,
      networkId: 80002,
      supportsEIP1559: true,
    ),
    tokenWalletType: TokenWalletType.child,
    description: 'USDC',
  ),
);

AppAsset polUSDCMockTestnetAmoyAssetExample({
  required String address,
}) => AppAsset(
  id: 3234,
  balance: BigRational.one,
  hold: BigRational.zero,
  address: address,
  walletId: 153,
  childWalletAddress: '',
  token: const AppToken(
    id: 235452,
    name: 'USDC',
    shortName: 'USDC',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png',
    usdPrice: 0.9995,
    prevPriceDiffPercent: 0.09,
    contractAddress: '0x8B0180f2101c8260d49339abfEe87927412494B4',
    decimal: 6,
    precision: 2,
    blockchain: BlockchainInfo(
      id: 436,
      name: 'Polygon Amoy',
      shortName: 'polygon',
      icon: '',
      isNew: true,
      tokens: [],
      appBlockchain: AppBlockchain.polygon,
      chainId: 80002,
      networkId: 80002,
      supportsEIP1559: true,
    ),
    tokenWalletType: TokenWalletType.child,
    description: 'USDC mock',
  ),
);

AppAsset polUSDCAssetExample({
  required String address,
}) => AppAsset(
  id: 3234,
  balance: BigRational.one,
  hold: BigRational.zero,
  address: address,
  walletId: 153,
  childWalletAddress: '',
  token: const AppToken(
    id: 235452,
    name: 'USDC',
    shortName: 'USDC',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png',
    usdPrice: 0.9995,
    prevPriceDiffPercent: 0.09,
    contractAddress: '0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359',
    decimal: 6,
    precision: 2,
    blockchain: BlockchainInfo(
      id: 4360,
      name: 'Polygon mainnet',
      shortName: 'polygon',
      icon: '',
      isNew: true,
      tokens: [],
      appBlockchain: AppBlockchain.polygon,
      chainId: 137,
      networkId: 137,
      supportsEIP1559: true,
    ),
    tokenWalletType: TokenWalletType.child,
    description: 'USDC',
  ),
);
